server:
  port: 8082

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/graduation?useSSL=false&useUnicode=true&characterEncoding=UTF8&serverTimezone=Asia/Shanghai
    username: web
    password: 123456

  redis:
    host: 192.168.100.100
    port: 6379

  rabbitmq:
    host: 192.168.100.100
    port: 5672
    username: admin
    password: admin
    virtual-host: /item
    #    开启发布确认
    publisher-confirm-type: correlated


mybatis-plus:
  #指定mybatis全局配置
  configuration:
    map-underscore-to-camel-case: true
    use-generated-keys: true

  global-config:
    db-config:
#      主键类型
      id-type: auto
#      驼峰转下划线命名
      table-underline: true
#      全局逻辑删除字段
      logic-delete-field: isDel
#      逻辑已删除(1)
      logic-delete-value: 1
#      逻辑未删除(0)
      logic-not-delete-value: 0

logging:
  level:
#    以debug方式在控制台打印执行的sql语句
    com.example.dao: debug


img:
  path: C:\Users\86183\Desktop\毕设\web\img\